### ISSUE TITLE
Warning: Indexing all PDF objects

### ISSUE THREAD

**Issue by lakshmankotipalli** [parrisvarney/ng-pdf-viewer#1]
Hi,

I am not able to view the pdf, and I included all the files as suggested. I am getting the following issue log. Pls help

```
Error: Invalid XRef stream header
pdf.worker.js:295     at error (http://localhost:3000/bower_components/pdfjs-dist/build/pdf.worker.js:295:17)
    at Object.XRef_readXRef [as readXRef] (http://localhost:3000/bower_components/pdfjs-dist/build/pdf.worker.js:23759:13)
    at Object.XRef_parse [as parse] (http://localhost:3000/bower_components/pdfjs-dist/build/pdf.worker.js:23342:28)
    at Object.PDFDocument_setup [as setup] (http://localhost:3000/bower_components/pdfjs-dist/build/pdf.worker.js:40015:17)
    at Object.PDFDocument_parse [as parse] (http://localhost:3000/bower_components/pdfjs-dist/build/pdf.worker.js:39896:12)
    at http://localhost:3000/bower_components/pdfjs-dist/build/pdf.worker.js:40205:28
    at LocalPdfManager_ensure [as ensure] (http://localhost:3000/bower_components/pdfjs-dist/build/pdf.worker.js:40200:14)
    at LocalPdfManager.BasePdfManager_ensureDoc [as ensureDoc] (http://localhost:3000/bower_components/pdfjs-dist/build/pdf.worker.js:40134:19)
    at http://localhost:3000/bower_components/pdfjs-dist/build/pdf.worker.js:40461:22
pdf.worker.js:281 Warning: Indexing all PDF objects

undefined:1 Uncaught (in promise) InvalidPDFException {name: "InvalidPDFException", message: "Invalid PDF structure"}message: "Invalid PDF structure"name: "InvalidPDFException"stack: (...)__proto__: Error
    at InvalidPDFExceptionClosure (http://localhost:3000/bower_components/pdfjs-dist/build/pdf.js:468:35)
    at http://localhost:3000/bower_components/pdfjs-dist/build/pdf.js:472:3
    at PDFJS (http://localhost:3000/bower_components/pdfjs-dist/build/pdf.js:61:5)
    at pdfjsWrapper (http://localhost:3000/bower_components/pdfjs-dist/build/pdf.js:63:2)
    at http://localhost:3000/bower_components/pdfjs-dist/build/pdf.js:9166:4
4commonfactory.js:6 9j8QhY2-tC6P2yudGSmHAQrequest @ commonfactory.js:6processQueue @ angular.js:16383(anonymous function) @ angular.js:16399$eval @ angular.js:17682$digest @ angular.js:17495$apply @ angular.js:17790(anonymous function) @ angular.js:19621completeOutstandingRequest @ angular.js:5964(anonymous function) @ angular.js:6243
```

**Comment by lakshmankotipalli** [comment]
sorry! my bad... i gave a wrong url
